const pakCity = [
  { value: "Abbottabad", label: "Abbottabad" },
  ,
  { value: "Adezai", label: "Adezai" },
  ,
  { value: "Ali Bandar", label: "Ali Bandar" },
  ,
  { value: "Amir Chah", label: "Amir Chah" },
  ,
  { value: "Attock", label: "Attock" },
  ,
  { value: "Ayubia", label: "Ayubia" },
  ,
  { value: "Bahawalpur", label: "Bahawalpur" },
  ,
  { value: "Baden", label: "Baden" },
  ,
  { value: "Bagh", label: "Bagh" },
  ,
  { value: "Bahawalnagar", label: "Bahawalnagar" },
  ,
  { value: "Burewala", label: "Burewala" },
  ,
  { value: "Banda Daud Shah", label: "Banda Daud Shah" },
  ,
  { value: "Bannu district|Bannu", label: "Bannu district|Bannu" },
  ,
  { value: "Batagram", label: "Batagram" },
  ,
  { value: "Bazdar", label: "Bazdar" },
  ,
  { value: "Bela", label: "Bela" },
  ,
  { value: "Bellpat", label: "Bellpat" },
  ,
  { value: "Bhag", label: "Bhag" },
  ,
  { value: "Bhakkar", label: "Bhakkar" },
  ,
  { value: "Bhalwal", label: "Bhalwal" },
  ,
  { value: "Bhimber", label: "Bhimber" },
  ,
  { value: "Birote", label: "Birote" },
  ,
  { value: "Buner", label: "Buner" },
  ,
  { value: "Burj", label: "Burj" },
  ,
  { value: "Chiniot", label: "Chiniot" },
  ,
  { value: "Chachro", label: "Chachro" },
  ,
  { value: "Chagai", label: "Chagai" },
  ,
  { value: "Chah Sandan", label: "Chah Sandan" },
  ,
  { value: "Chailianwala", label: "Chailianwala" },
  ,
  { value: "Chakdara", label: "Chakdara" },
  ,
  { value: "Chakku", label: "Chakku" },
  ,
  { value: "Chakwal", label: "Chakwal" },
  ,
  { value: "Chaman", label: "Chaman" },
  ,
  { value: "Charsadda", label: "Charsadda" },
  ,
  { value: "Chhatr", label: "Chhatr" },
  ,
  { value: "Chichawatni", label: "Chichawatni" },
  ,
  { value: "Chitral", label: "Chitral" },
  ,
  { value: "Dadu", label: "Dadu" },
  ,
  { value: "Dera Ghazi Khan", label: "Dera Ghazi Khan" },
  ,
  { value: "Dera Ismail Khan", label: "Dera Ismail Khan" },
  { value: "Dalbandin", label: "Dalbandin" },
  ,
  { value: "Dargai", label: "Dargai" },
  ,
  { value: "Darya Khan", label: "Darya Khan" },
  ,
  { value: "Daska", label: "Daska" },
  ,
  { value: "Dera Bugti", label: "Dera Bugti" },
  ,
  { value: "Dhana Sar", label: "Dhana Sar" },
  ,
  { value: "Digri", label: "Digri" },
  ,
  { value: "Dina City|Dina", label: "Dina City|Dina" },
  ,
  { value: "Dinga", label: "Dinga" },
  ,
  { value: "Diplo", label: "Diplo" },
  ,
  { value: "Diwana", label: "Diwana" },
  ,
  { value: "Dokri", label: "Dokri" },
  ,
  { value: "Drosh", label: "Drosh" },
  ,
  { value: "Duki", label: "Duki" },
  ,
  { value: "Dushi", label: "Dushi" },
  ,
  { value: "Duzab", label: "Duzab" },
  ,
  { value: "Faisalabad", label: "Faisalabad" },
  ,
  { value: "Fateh Jang", label: "Fateh Jang" },
  ,
  { value: "Ghotki", label: "Ghotki" },
  ,
  { value: "Gwadar", label: "Gwadar" },
  ,
  { value: "Gujranwala", label: "Gujranwala" },
  ,
  { value: "Gujrat", label: "Gujrat" },
  ,
  { value: "Gadra", label: "Gadra" },
  ,
  { value: "Gajar", label: "Gajar" },
  ,
  { value: "Gandava", label: "Gandava" },
  ,
  { value: "Garhi Khairo", label: "Garhi Khairo" },
  ,
  { value: "Garruck", label: "Garruck" },
  ,
  { value: "Ghakhar Mandi", label: "Ghakhar Mandi" },
  ,
  { value: "Ghanian", label: "Ghanian" },
  ,
  { value: "Ghauspur", label: "Ghauspur" },
  ,
  { value: "Ghazluna", label: "Ghazluna" },
  ,
  { value: "Girdan", label: "Girdan" },
  ,
  { value: "Gulistan", label: "Gulistan" },
  ,
  { value: "Gwash", label: "Gwash" },
  ,
  { value: "Hyderabad", label: "Hyderabad" },
  ,
  { value: "Hala", label: "Hala" },
  ,
  { value: "Haripur", label: "Haripur" },
  ,
  { value: "Hab Chauki", label: "Hab Chauki" },
  ,
  { value: "Hafizabad", label: "Hafizabad" },
  ,
  { value: "Hameedabad", label: "Hameedabad" },
  ,
  { value: "Hangu", label: "Hangu" },
  ,
  { value: "Harnai", label: "Harnai" },
  ,
  { value: "Hasilpur", label: "Hasilpur" },
  ,
  { value: "Haveli Lakha", label: "Haveli Lakha" },
  ,
  { value: "Hinglaj", label: "Hinglaj" },
  ,
  { value: "Hoshab", label: "Hoshab" },
  ,
  { value: "Islamabad", label: "Islamabad" },
  ,
  { value: "Islamkot", label: "Islamkot" },
  ,
  { value: "Ispikan", label: "Ispikan" },
  ,
  { value: "Jacobabad", label: "Jacobabad" },
  ,
  { value: "Jamshoro", label: "Jamshoro" },
  ,
  { value: "Jhang", label: "Jhang" },
  ,
  { value: "Jhelum", label: "Jhelum" },
  ,
  { value: "Jamesabad", label: "Jamesabad" },
  ,
  { value: "Jampur", label: "Jampur" },
  { value: "Janghar", label: "Janghar" },
  ,
  { value: "Jati(Mughalbhin)", label: "Jati(Mughalbhin)" },
  ,
  { value: "Jauharabad", label: "Jauharabad" },
  ,
  { value: "Jhal", label: "Jhal" },
  ,
  { value: "Jhal Jhao", label: "Jhal Jhao" },
  ,
  { value: "Jhatpat", label: "Jhatpat" },
  ,
  { value: "Jhudo", label: "Jhudo" },
  ,
  { value: "Jiwani", label: "Jiwani" },
  ,
  { value: "Jungshahi", label: "Jungshahi" },
  ,
  { value: "Karachi", label: "Karachi" },
  ,
  { value: "Kotri", label: "Kotri" },
  ,
  { value: "Kalam", label: "Kalam" },
  ,
  { value: "Kalandi", label: "Kalandi" },
  ,
  { value: "Kalat", label: "Kalat" },
  ,
  { value: "Kamalia", label: "Kamalia" },
  ,
  { value: "Kamararod", label: "Kamararod" },
  ,
  { value: "Kamber", label: "Kamber" },
  ,
  { value: "Kamokey", label: "Kamokey" },
  ,
  { value: "Kanak", label: "Kanak" },
  ,
  { value: "Kandi", label: "Kandi" },
  ,
  { value: "Kandiaro", label: "Kandiaro" },
  ,
  { value: "Kanpur", label: "Kanpur" },
  ,
  { value: "Kapip", label: "Kapip" },
  ,
  { value: "Kappar", label: "Kappar" },
  ,
  { value: "Karak City", label: "Karak City" },
  ,
  { value: "Karodi", label: "Karodi" },
  ,
  { value: "Kashmor", label: "Kashmor" },
  ,
  { value: "Kasur", label: "Kasur" },
  ,
  { value: "Katuri", label: "Katuri" },
  ,
  { value: "Keti Bandar", label: "Keti Bandar" },
  ,
  { value: "Khairpur", label: "Khairpur" },
  ,
  { value: "Khanaspur", label: "Khanaspur" },
  ,
  { value: "Khanewal", label: "Khanewal" },
  ,
  { value: "Kharan", label: "Kharan" },
  ,
  { value: "kharian", label: "kharian" },
  ,
  { value: "Khokhropur", label: "Khokhropur" },
  ,
  { value: "Khora", label: "Khora" },
  ,
  { value: "Khushab", label: "Khushab" },
  ,
  { value: "Khuzdar", label: "Khuzdar" },
  ,
  { value: "Kikki", label: "Kikki" },
  ,
  { value: "Klupro", label: "Klupro" },
  ,
  { value: "Kohan", label: "Kohan" },
  ,
  { value: "Kohat", label: "Kohat" },
  ,
  { value: "Kohistan", label: "Kohistan" },
  ,
  { value: "Kohlu", label: "Kohlu" },
  ,
  { value: "Korak", label: "Korak" },
  ,
  { value: "Korangi", label: "Korangi" },
  ,
  { value: "Kot Sarae", label: "Kot Sarae" },
  ,
  { value: "Kotli", label: "Kotli" },
  ,
  { value: "Lahore", label: "Lahore" },
  ,
  { value: "Larkana", label: "Larkana" },
  ,
  { value: "Lahri", label: "Lahri" },
  ,
  { value: "Lakki Marwat", label: "Lakki Marwat" },
  ,
  { value: "Lasbela", label: "Lasbela" },
  ,
  { value: "Latamber", label: "Latamber" },
  ,
  { value: "Layyah", label: "Layyah" },
  ,
  { value: "Leiah", label: "Leiah" },
  ,
  { value: "Liari", label: "Liari" },
  ,
  { value: "Lodhran", label: "Lodhran" },
  ,
  { value: "Loralai", label: "Loralai" },
  ,
  { value: "Lower Dir", label: "Lower Dir" },
  ,
  { value: "Shadan Lund", label: "Shadan Lund" },
  ,
  { value: "Multan", label: "Multan" },
  ,
  { value: "Mandi Bahauddin", label: "Mandi Bahauddin" },
  ,
  { value: "Mansehra", label: "Mansehra" },
  ,
  { value: "Mian Chanu", label: "Mian Chanu" },
  ,
  { value: "Mirpur", label: "Mirpur" },
  ,
  { value: "Moro", label: "Moro" },
  ,
  { value: "Mardan", label: "Mardan" },
  ,
  { value: "Mach", label: "Mach" },
  ,
  { value: "Madyan", label: "Madyan" },
  ,
  { value: "Malakand", label: "Malakand" },
  ,
  { value: "Mand", label: "Mand" },
  ,
  { value: "Manguchar", label: "Manguchar" },
  ,
  { value: "Mashki Chah", label: "Mashki Chah" },
  ,
  { value: "Maslti", label: "Maslti" },
  ,
  { value: "Mastuj", label: "Mastuj" },
  ,
  { value: "Mastung", label: "Mastung" },
  ,
  { value: "Mathi", label: "Mathi" },
  ,
  { value: "Matiari", label: "Matiari" },
  ,
  { value: "Mehar", label: "Mehar" },
  ,
  { value: "Mekhtar", label: "Mekhtar" },
  ,
  { value: "Merui", label: "Merui" },
  ,
  { value: "Mianwali", label: "Mianwali" },
  ,
  { value: "Mianez", label: "Mianez" },
  ,
  { value: "Mirpur Batoro", label: "Mirpur Batoro" },
  ,
  { value: "Mirpur Khas", label: "Mirpur Khas" },
  ,
  { value: "Mirpur Sakro", label: "Mirpur Sakro" },
  ,
  { value: "Mithi", label: "Mithi" },
  ,
  { value: "Mongora", label: "Mongora" },
  ,
  { value: "Murgha Kibzai", label: "Murgha Kibzai" },
  ,
  { value: "Muridke", label: "Muridke" },
  ,
  { value: "Musa Khel Bazar", label: "Musa Khel Bazar" },
  ,
  { value: "Muzaffar Garh", label: "Muzaffar Garh" },
  ,
  { value: "Muzaffarabad", label: "Muzaffarabad" },
  { value: "Nawabshah", label: "Nawabshah" },
  ,
  { value: "Nazimabad", label: "Nazimabad" },
  ,
  { value: "Nowshera", label: "Nowshera" },
  ,
  { value: "Nagar Parkar", label: "Nagar Parkar" },
  ,
  { value: "Nagha Kalat", label: "Nagha Kalat" },
  ,
  { value: "Nal", label: "Nal" },
  ,
  { value: "Naokot", label: "Naokot" },
  ,
  { value: "Nasirabad", label: "Nasirabad" },
  ,
  { value: "Nauroz Kalat", label: "Nauroz Kalat" },
  ,
  { value: "Naushara", label: "Naushara" },
  ,
  { value: "Nur Gamma", label: "Nur Gamma" },
  ,
  { value: "Nushki", label: "Nushki" },
  ,
  { value: "Nuttal", label: "Nuttal" },
  ,
  { value: "Okara", label: "Okara" },
  ,
  { value: "Ormara", label: "Ormara" },
  ,
  { value: "Peshawar", label: "Peshawar" },
  ,
  { value: "Panjgur", label: "Panjgur" },
  ,
  { value: "Pasni City", label: "Pasni City" },
  ,
  { value: "Paharpur", label: "Paharpur" },
  ,
  { value: "Palantuk", label: "Palantuk" },
  ,
  { value: "Pendoo", label: "Pendoo" },
  ,
  { value: "Piharak", label: "Piharak" },
  ,
  { value: "Pirmahal", label: "Pirmahal" },
  ,
  { value: "Pishin", label: "Pishin" },
  ,
  { value: "Plandri", label: "Plandri" },
  ,
  { value: "Pokran", label: "Pokran" },
  ,
  { value: "Pounch", label: "Pounch" },
  ,
  { value: "Quetta", label: "Quetta" },
  ,
  { value: "Qambar", label: "Qambar" },
  ,
  { value: "Qamruddin Karez", label: "Qamruddin Karez" },
  ,
  { value: "Qazi Ahmad", label: "Qazi Ahmad" },
  ,
  { value: "Qila Abdullah", label: "Qila Abdullah" },
  ,
  { value: "Qila Ladgasht", label: "Qila Ladgasht" },
  ,
  { value: "Qila Safed", label: "Qila Safed" },
  ,
  { value: "Qila Saifullah", label: "Qila Saifullah" },
  ,
  { value: "Rawalpindi", label: "Rawalpindi" },
  ,
  { value: "Rabwah", label: "Rabwah" },
  ,
  { value: "Rahim Yar Khan", label: "Rahim Yar Khan" },
  ,
  { value: "Rajan Pur", label: "Rajan Pur" },
  ,
  { value: "Rakhni", label: "Rakhni" },
  ,
  { value: "Ranipur", label: "Ranipur" },
  ,
  { value: "Ratodero", label: "Ratodero" },
  ,
  { value: "Rawalakot", label: "Rawalakot" },
  ,
  { value: "Renala Khurd", label: "Renala Khurd" },
  ,
  { value: "Robat Thana", label: "Robat Thana" },
  ,
  { value: "Rodkhan", label: "Rodkhan" },
  ,
  { value: "Rohri", label: "Rohri" },
  ,
  { value: "Sialkot", label: "Sialkot" },
  ,
  { value: "Sadiqabad", label: "Sadiqabad" },
  ,
  {
    value: "Safdar Abad- (Dhaban Singh)",
    label: "Safdar Abad- (Dhaban Singh)",
  },
  ,
  { value: "Sahiwal", label: "Sahiwal" },
  ,
  { value: "Saidu Sharif", label: "Saidu Sharif" },
  ,
  { value: "Saindak", label: "Saindak" },
  ,
  { value: "Sakrand", label: "Sakrand" },
  ,
  { value: "Sanjawi", label: "Sanjawi" },
  ,
  { value: "Sargodha", label: "Sargodha" },
  ,
  { value: "Saruna", label: "Saruna" },
  ,
  { value: "Shabaz Kalat", label: "Shabaz Kalat" },
  ,
  { value: "Shadadkhot", label: "Shadadkhot" },
  ,
  { value: "Shahbandar", label: "Shahbandar" },
  ,
  { value: "Shahpur", label: "Shahpur" },
  ,
  { value: "Shahpur Chakar", label: "Shahpur Chakar" },
  ,
  { value: "Shakargarh", label: "Shakargarh" },
  ,
  { value: "Shangla", label: "Shangla" },
  ,
  { value: "Sharam Jogizai", label: "Sharam Jogizai" },
  ,
  { value: "Sheikhupura", label: "Sheikhupura" },
  ,
  { value: "Shikarpur", label: "Shikarpur" },
  ,
  { value: "Shingar", label: "Shingar" },
  ,
  { value: "Shorap", label: "Shorap" },
  ,
  { value: "Sibi", label: "Sibi" },
  ,
  { value: "Sohawa", label: "Sohawa" },
  ,
  { value: "Sonmiani", label: "Sonmiani" },
  ,
  { value: "Sooianwala", label: "Sooianwala" },
  ,
  { value: "Spezand", label: "Spezand" },
  ,
  { value: "Spintangi", label: "Spintangi" },
  ,
  { value: "Sui", label: "Sui" },
  ,
  { value: "Sujawal", label: "Sujawal" },
  ,
  { value: "Sukkur", label: "Sukkur" },
  ,
  { value: "Suntsar", label: "Suntsar" },
  ,
  { value: "Surab", label: "Surab" },
  ,
  { value: "Swabi", label: "Swabi" },
  ,
  { value: "Swat", label: "Swat" },
  ,
  { value: "Tando Adam", label: "Tando Adam" },
  ,
  { value: "Tando Bago", label: "Tando Bago" },
  ,
  { value: "Tangi", label: "Tangi" },
  ,
  { value: "Tank City", label: "Tank City" },
  ,
  { value: "Tar Ahamd Rind", label: "Tar Ahamd Rind" },
  ,
  { value: "Thalo", label: "Thalo" },
  ,
  { value: "Thatta", label: "Thatta" },
  ,
  { value: "Toba Tek Singh", label: "Toba Tek Singh" },
  ,
  { value: "Tordher", label: "Tordher" },
  ,
  { value: "Tujal", label: "Tujal" },
  ,
  { value: "Tump", label: "Tump" },
  ,
  { value: "Turbat", label: "Turbat" },
  ,
  { value: "Umarao", label: "Umarao" },
  ,
  { value: "Umarkot", label: "Umarkot" },
  ,
  { value: "Upper Dir", label: "Upper Dir" },
  ,
  { value: "Uthal", label: "Uthal" },
  ,
  { value: "Vehari", label: "Vehari" },
  ,
  { value: "Veirwaro", label: "Veirwaro" },
  ,
  { value: "Vitakri", label: "Vitakri" },
  ,
  { value: "Wadh", label: "Wadh" },
  ,
  { value: "Wah Cantt", label: "Wah Cantt" },
  ,
  { value: "Warah", label: "Warah" },
  ,
  { value: "Washap", label: "Washap" },
  { value: "Wasjuk", label: "Wasjuk" },
  { value: "Wazirabad", label: "Wazirabad" },
  { value: "Yakmach", label: "Yakmach" },
  { value: "Zhob", label: "Zhob" },
  { value: "Other", label: "Other" },
];

export default pakCity;
